BoardGames/Models/BoardGame.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using LinqToDB.Mapping;

namespace BoardGames.Models
{
    [Table]
    public class BoardGame
    {
        [PrimaryKey, Identity]
        public int Id { get; set; }

        [Display(Name = "Название"), Column]
        public string Name { get; set; }

        [Display(Name = "Производитель"), Column]
        public string CreatedBy { get; set; }

        [Display(Name = "Минимальное число игроков"), Column]
        public int MinPlayers { get; set; }

        [Display(Name = "Максимальное число игроков"), Column]
        public int MaxPlayers { get; set; }

        [Display(Name = "Осталось в наличии"), Column]
        public int LeftAmount { get; set; }

        [Display(Name = "Короткое описание"), Column]
        public string ShortDescription { get; set; }

        [Display(Name = "Цена"), Column]
        public int Price { get; set; }
        
        [Display(Name = "Число отзывов"), Column]
        public int CountReview { get; set; }
        
        [Display(Name = "Оценка"), Column]
        public int AverageMark { get; set; }

        public void Update(BoardGame boardGame)
        {
            Name = boardGame.Name;
            CreatedBy = boardGame.CreatedBy;
            MinPlayers = boardGame.MinPlayers;
            MaxPlayers = boardGame.MaxPlayers;
            LeftAmount = boardGame.LeftAmount;
            ShortDescription = boardGame.ShortDescription;
            Price = boardGame.Price;
            CountReview = boardGame.CountReview;
            AverageMark = boardGame.AverageMark;
        }

        public List<Review> Reviews { get; set; }
    }
}

BoardGames/Controllers/BoardGameController.cs
using System;
using System.Web.Mvc;
using BoardGames.Models;

namespace BoardGames.Controllers
{
    public class BoardGameController : Controller
    {

        private const int _PAGE_SIZE = 10;
        private IBoardGameContext _boardGameContext;

        public BoardGameController() : this(new DbBoardGameContext())
        {
        }

        public BoardGameController(IBoardGameContext boardGameContext)
        {
            _boardGameContext = boardGameContext ?? throw new ArgumentNullException();
        }

        public ActionResult List(int currentPage = 1)
        {
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            var paginatorNum = currentPage - 2;
            if (paginatorNum < 1)
            {
                paginatorNum = 1;
            }
            var indexListView = new IndexListView()
            {
                BoardGames = _boardGameContext.GetRange((currentPage - 1) * _PAGE_SIZE, _PAGE_SIZE),
                CurrentPage = paginatorNum,
                TotalPage = (_boardGameContext.Count() + _PAGE_SIZE  - 1) / _PAGE_SIZE
            };
            return View(indexListView);
        }

        public ActionResult Top20()
        {
            var boardGames = _boardGameContext.GetTop20();
            return View(boardGames);
        }

        public ActionResult Details(int id = 0)
        {
            ViewBag.Title = "Подробнее о настольной игре";
            var boardGame = _boardGameContext.GetBoardGame(id);

            if (boardGame == null)
                return HttpNotFound();

            return View(boardGame);
        }
        
        [HttpPost]
        public void AddMark(int boardGameId, int mark)
        {
            _boardGameContext.AddMark(boardGameId, mark);
        } 

        public ActionResult Edit(int id = 0)
        {
            var boardGame = _boardGameContext.GetBoardGame(id);

            if (boardGame == null)
                return HttpNotFound();

            return View(boardGame);
        }
        
        [HttpPost]
        public ActionResult Edit(BoardGame editBoardGame)
        {
            var first = _boardGameContext.GetBoardGame(editBoardGame.Id);

            if (first == null)
                return HttpNotFound();

            _boardGameContext.Update(editBoardGame);

            return RedirectToAction("Details", "BoardGame", new {id = editBoardGame.Id});
        }
        
        public ActionResult Create()
        {
            return View(new BoardGame());
        }
        
        [HttpPost]
        public ActionResult Create(BoardGame boardGame)
        {
            if (ModelState.IsValid)
            {
                _boardGameContext.AddBoardGame(boardGame);
            }
            else
            {
                ModelState.AddModelError("Create", "Something went wrong!");
            }
            return RedirectToAction("List", "BoardGame");
        }

    }
}

BoardGames/Controllers/ReviewController.cs
using System;
using System.Web.Mvc;
using BoardGames.Models;

namespace BoardGames.Controllers
{
    public class ReviewController : Controller
    {
        private IBoardGameContext _boardGameContext;
        private IReviewContext _reviewContext;

        public ReviewController() : this(new DbBoardGameContext(), new DbReviewContext())
        {
        }

        public ReviewController(IBoardGameContext boardGameContext, IReviewContext reviewContext)
        {
            _boardGameContext = boardGameContext ?? throw new ArgumentNullException();
            _reviewContext = reviewContext ?? throw new ArgumentNullException();
        }

        public ActionResult Create(int boardGameId)
        {
            if (_boardGameContext.GetBoardGame(boardGameId) == null)
                return HttpNotFound();

            var review = new Review {BoardGameId = boardGameId };
            
            return View(review);
        }

        [HttpPost]
        public ActionResult Create(Review review)
        {
            if (ModelState.IsValid)
            {
                _boardGameContext.AddReview(review);
            }
            else
            {
                ModelState.AddModelError("Create", "Something wrong!");
            }
            return RedirectToAction("Details", "BoardGame", new { id = review.BoardGameId });
        }

        [HttpPost]
        public int IncrementAndGetLikes(int reviewId)
        {
            var likesCount = _reviewContext.IncrementAndGetLikes(reviewId);
            if (likesCount != -1) return likesCount;
            Response.StatusCode = 404;
            return -1;
        }

        [HttpPost]
        public void ReportOffensiveReview(int reviewId, string reason)
        {
            _reviewContext.Report(reviewId, reason);
        }
    }
}

BoardGames/Views/BoardGame/Create.cshtml
@using BoardGames.Models;
@model BoardGame

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  
@using (Html.BeginForm()) {    
    <fieldset>
        <legend>BoardGame</legend>
    
        @Html.HiddenFor(model => model.Id)
    
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedBy)
            @Html.ValidationMessageFor(model => model.CreatedBy)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.MinPlayers)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MinPlayers)
            @Html.ValidationMessageFor(model => model.MinPlayers)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.MaxPlayers)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaxPlayers)
            @Html.ValidationMessageFor(model => model.MaxPlayers)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.LeftAmount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LeftAmount)
            @Html.ValidationMessageFor(model => model.LeftAmount)
        </div>        
        
        <div class="editor-label">
            @Html.LabelFor(model => model.ShortDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ShortDescription)
            @Html.ValidationMessageFor(model => model.ShortDescription)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
    
        <p>
            <input type="submit" value="Добавить" />
        </p>
    </fieldset>
}
    
<div>
    @Html.ActionLink("Вернуться к списку", "List")
</div>

BoardGames/Views/BoardGame/Details.cshtml
@using BoardGames.Models
@model BoardGame

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<fieldset>
    <h2>Настольная игра</h2>
    
    <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
    
    <b>
        @Html.DisplayNameFor(model => model.CreatedBy):
    </b>
    <span>
        @Html.DisplayFor(model => model.CreatedBy)
    </span>
    <br/>
    <b>
        @Html.DisplayNameFor(model => model.MinPlayers):
    </b>
    <span>
        @Html.DisplayFor(model => model.MinPlayers)
    </span>
    <br />
    <b>
        @Html.DisplayNameFor(model => model.MaxPlayers):
    </b>
    <span>
        @Html.DisplayFor(model => model.MaxPlayers)
    </span>
    <br />
    <b>
        @Html.DisplayNameFor(model => model.LeftAmount):
    </b>
    <span>
        @Html.DisplayFor(model => model.LeftAmount)
    </span>
    <br />
    <b>
        @Html.DisplayNameFor(model => model.ShortDescription):
    </b>
    <span>
        @Html.DisplayFor(model => model.ShortDescription)
    </span>
    <br />
    <b>
        @Html.DisplayNameFor(model => model.Price):
    </b>
    <span>
        @Html.DisplayFor(model => model.Price)
    </span>
    <br />
    <b>
        @Html.DisplayNameFor(model => model.AverageMark):
    </b>
    <span class="mark">
        @Html.DisplayFor(model => model.AverageMark, new { @class = "mark" })
    </span>
    <br />
    <span><b> Проголосовать: </b></span>
    <span class="like-btn-1" data-board-game="@Model.Id">
        &#10084;   
     </span>
    <span class="like-btn-2" data-board-game="@Model.Id">
        &#10084;   
     </span>
    <span class="like-btn-3" data-board-game="@Model.Id">
        &#10084;   
     </span>
    <span class="like-btn-4" data-board-game="@Model.Id">
        &#10084;   
     </span>
    <span class="like-btn-5" data-board-game="@Model.Id">
        &#10084;   
     </span>
</fieldset>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться к списку", "List") |
    @Html.ActionLink("Добавить отзыв", "Create", "Review", new { boardGameId = Model.Id }, null)
</p>	   

@Html.Partial("ReviewPartial", Model.Reviews)

BoardGames/Views/BoardGame/Edit.cshtml
@using BoardGames.Models;
@model BoardGame

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  
@using (Html.BeginForm()) {    
    <fieldset>
        <legend>BoardGame</legend>
    
        @Html.HiddenFor(model => model.Id)
    
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedBy)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.MinPlayers)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MinPlayers)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.MaxPlayers)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaxPlayers)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(model => model.LeftAmount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LeftAmount)
        </div>        
        
        
        <div class="editor-label">
            @Html.LabelFor(model => model.ShortDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ShortDescription)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
        </div>
    
        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}
    
<div>
    @Html.ActionLink("Вернуться к списку", "List")
</div>

BoardGames/Views/BoardGame/List.cshtml
@using BoardGames.Models;
@model IndexListView

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Название</th>
        <th scope="col">Производитель</th>
        <th scope="col">Минимальное число игроков</th>
        <th scope="col">Максимальное число игроков</th>
        <th scope="col">Осталось в наличии</th>
        <th scope="col">Короткое описание</th>
        <th scope="col">Цена</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var boardGame in Model.BoardGames)
    {
        <tr data="@boardGame.Id" onclick="window.location.href='/BoardGame/Details/' + this.getAttribute('data')">
            <td>@boardGame.Name</td>
            <td>@boardGame.CreatedBy</td>
            <td>@boardGame.MinPlayers</td>
            <td>@boardGame.MaxPlayers</td>
            <td>@boardGame.LeftAmount</td>
            <td>@boardGame.ShortDescription</td>
            <td>@boardGame.Price</td>
        </tr>
    } 
    </tbody>
</table>
<style>
    tr:hover {
        cursor: pointer;
        background: #f0f0f0;
    }
</style>

<hr/>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        @foreach (var index in Enumerable.Range(Model.CurrentPage, 5))
        {
            <li class="page-item">
                @Html.ActionLink(index.ToString(), "List", new {currentPage = index}, new { @class = "page-link" })
            </li>
        } 
    </ul>
</nav>   

BoardGames/Views/BoardGame/Top20.cshtml
@using BoardGames.Models;
@model List<BoardGame>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Царство</th>
        <th scope="col">Отдел</th>
        <th scope="col">Класс</th>
        <th scope="col">Домен</th>
        <th scope="col">Семейство</th>
        <th scope="col">Порядок</th>
        <th scope="col">Род</th>
        <th scope="col">Количество отзывов</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var boardGame in Model)
    {
        <tr data="@boardGame.Id" onclick="window.location.href='/BoardGame/Details/' + this.getAttribute('data')">
            <td>@boardGame.Name</td>
            <td>@boardGame.CreatedBy</td>
            <td>@boardGame.MinPlayers</td>
            <td>@boardGame.MaxPlayers</td>
            <td>@boardGame.LeftAmount</td>
            <td>@boardGame.ShortDescription</td>
            <td>@boardGame.Price</td>
            <td>@boardGame.CountReview</td>
        </tr>
    } 
    </tbody>
</table>
<style>
    tr:hover {
        cursor: pointer;
        background: #f0f0f0;
    }
</style>

<hr/>